Repository DSM-TeaMit/Nutella, pull requests merged in 2022-01, with the labels that each got.

#2 1 Project Setting
  nutella/.gitignore
  nutella/README.md
  nutella/package-lock.json
  nutella/package.json
  nutella/public/favicon.ico
  nutella/public/index.html
  nutella/public/logo192.png
  nutella/public/logo512.png
  nutella/public/manifest.json
  nutella/public/robots.txt
  nutella/src/App.css
  nutella/src/App.test.tsx
  nutella/src/App.tsx
  nutella/src/index.css
  nutella/src/index.tsx
  nutella/src/logo.svg
  nutella/src/react-app-env.d.ts
  nutella/src/reportWebVitals.ts
  nutella/src/setupTests.ts
  nutella/tsconfig.json
Labels: style

#10 9 Setting File Structure
  nutella/src/assets/index.ts
  nutella/src/components/index.ts
  nutella/src/constant/index.ts
  nutella/src/container/index.ts
  nutella/src/hooks/index.ts
  nutella/src/interface/index.ts
  nutella/src/route/index.ts
  nutella/src/style/index.ts
  nutella/src/utils/api/index.ts
Labels: style

#7 5 Delete Useless File
  nutella/src/App.css
  nutella/src/App.test.tsx
  nutella/src/App.tsx
  nutella/src/index.css
  nutella/src/index.tsx
  nutella/src/logo.svg
  nutella/src/reportWebVitals.ts
  nutella/src/setupTests.ts
Labels: document

#12 8 Add Theme
  nutella/@types/emotion/index.d.ts
  nutella/package-lock.json
  nutella/package.json
  nutella/src/App.tsx
  nutella/src/style/index.ts
  nutella/src/style/theme.ts
  nutella/tsconfig.json
Labels: new

#17 16 Write Global Style
  nutella/src/App.tsx
  nutella/src/style/globalStyle.ts
  nutella/src/style/theme.ts
Labels: new

#19 15 Make Route Structure
  nutella/src/App.tsx
  nutella/src/hooks/index.ts
  nutella/src/route/MainRouter.tsx
  nutella/src/route/RootRouter.tsx
  nutella/src/route/index.ts
Labels: new

#20 13 Publishing Header
  nutella/src/assets/icons/arrow.svg
  nutella/src/assets/icons/index.ts
  nutella/src/assets/logo/Logo.svg
  nutella/src/components/Header/Header.tsx
  nutella/src/components/Header/SearchInput/index.tsx
  nutella/src/components/Header/SearchInput/styles.ts
  nutella/src/components/Header/styles.ts
  nutella/src/style/globalStyle.ts
Labels: publishing

#21 14 Publishing Footer
  nutella/src/assets/icons/github.svg
  nutella/src/assets/icons/rightArrow.svg
  nutella/src/components/Footer/Footer.tsx
  nutella/src/components/Footer/styles.ts
  nutella/src/components/Header/Header.tsx
  nutella/src/components/Header/styles.ts
Labels: publishing

#24 23 Change Header And Footer Style
  nutella/src/components/Header/styles.ts
Labels: publishing, modify

#29 28 Publishing Search
  nutella/src/assets/icons/index.ts
  nutella/src/assets/icons/profile.svg
  nutella/src/assets/icons/projectPhoto.svg
  nutella/src/assets/icons/view.svg
  nutella/src/components/Project/Project.tsx
  nutella/src/components/Project/styles.ts
  nutella/src/components/Search/Search.tsx
  nutella/src/components/Search/styles.ts
  nutella/src/container/Search/index.tsx
  nutella/src/container/index.ts
  nutella/src/route/MainRouter.tsx
Labels: publishing

#25 3 Publishing Login
  nutella/src/assets/icons/line.svg
  nutella/src/assets/logo/GoogleLogo.svg
  nutella/src/assets/logo/LoginLogo.svg
  nutella/src/components/Login/Login.tsx
  nutella/src/components/Login/styles.ts
  nutella/src/route/MainRouter.tsx
Labels: publishing

#31 30 Add Login Container
  nutella/src/container/Login/index.tsx
  nutella/src/container/index.ts
  nutella/src/route/MainRouter.tsx
Labels: modify

#33 32 Modify Duplicated Code
  nutella/src/components/Search/Search.tsx
Labels: refactoring

#34 22 Publishing Mypage
  nutella/package-lock.json
  nutella/package.json
  nutella/src/assets/icons/arrow_black.svg
  nutella/src/assets/icons/club.svg
  nutella/src/assets/icons/document.svg
  nutella/src/assets/icons/document_edit.svg
  nutella/src/assets/icons/github_black.svg
  nutella/src/assets/icons/personal.svg
  nutella/src/assets/icons/setting.svg
  nutella/src/assets/icons/team.svg
  nutella/src/assets/icons/up_arrow.svg
  nutella/src/components/MarkdownRender/index.tsx
  nutella/src/components/MarkdownRender/styles.ts
  nutella/src/components/Mypage/Contents/Profile.tsx
  nutella/src/components/Mypage/Contents/Project.tsx
  nutella/src/components/Mypage/Contents/Report.tsx
  nutella/src/components/Mypage/Contents/ReportAccordion/index.tsx
  nutella/src/components/Mypage/Contents/ReportAccordion/styles.ts
  nutella/src/components/Mypage/Contents/Setting.tsx
  nutella/src/components/Mypage/Contents/styles.ts
  nutella/src/components/Mypage/Mypage.tsx
  nutella/src/components/Mypage/SideBar/Navigation/index.tsx
  nutella/src/components/Mypage/SideBar/Navigation/styles.ts
  nutella/src/components/Mypage/SideBar/index.tsx
  nutella/src/components/Mypage/SideBar/styles.ts
  nutella/src/components/Mypage/styles.ts
  nutella/src/components/ProjectCard/index.tsx
  nutella/src/components/ProjectCard/styles.ts
  nutella/src/components/ReportCard/index.tsx
  nutella/src/components/ReportCard/styles.ts
  nutella/src/container/Mypage/index.tsx
  nutella/src/container/index.ts
  nutella/src/interface/Navigation.ts
  nutella/src/interface/State.ts
  nutella/src/interface/index.ts
  nutella/src/route/MainRouter.tsx
  nutella/src/style/globalStyle.ts
  nutella/src/utils/theme/theme.ts
Labels: publishing

#37 35 Realize Modal
  nutella/public/index.html
  nutella/src/App.tsx
  nutella/src/components/ModalController/index.tsx
  nutella/src/components/ModalController/styles.ts
  nutella/src/components/Mypage/Contents/Setting.tsx
  nutella/src/context/ModalContext.tsx
  nutella/src/hooks/useInput.ts
  nutella/src/hooks/useInputs.ts
  nutella/src/hooks/useModalContext.ts
Labels: new

#40 39 Divide Modal Context And Modal Provider
  nutella/src/App.tsx
  nutella/src/components/ModalController/index.tsx
  nutella/src/components/Providers/ModalProvider.tsx
  nutella/src/context/ModalContext.ts
Labels: modify

#41 38 Realize Message
  nutella/public/index.html
  nutella/src/App.tsx
  nutella/src/components/Message/DenialMessage.tsx
  nutella/src/components/Message/PositiveMessage.tsx
  nutella/src/components/Message/styles.ts
  nutella/src/components/MessageController/index.tsx
  nutella/src/components/MessageController/styles.ts
  nutella/src/components/Providers/MessageProvider.tsx
  nutella/src/context/MessageContext.ts
  nutella/src/hooks/useMessageContext.ts
Labels: new

#44 42 Change Header Style
  nutella/src/components/Header/styles.ts
  nutella/src/components/Mypage/Contents/Profile.tsx
  nutella/src/components/Mypage/Contents/Project.tsx
  nutella/src/components/Mypage/Contents/ReportAccordion/index.tsx
Labels: publishing, modify

#45 36 Add Index In Assets
  nutella/src/assets/icons/index.ts
  nutella/src/assets/logo/index.ts
  nutella/src/components/Footer/Footer.tsx
  nutella/src/components/Header/Header.tsx
  nutella/src/components/Login/Login.tsx
  nutella/src/components/Mypage/Contents/Profile.tsx
  nutella/src/components/Mypage/Contents/ReportAccordion/index.tsx
  nutella/src/components/Mypage/Contents/Setting.tsx
  nutella/src/components/Mypage/Mypage.tsx
  nutella/src/components/Project/Project.tsx
  nutella/src/components/ProjectCard/index.tsx
Labels: refactoring

#46 43 Add Project Add On Function In Project Section
  nutella/src/components/MemberInput/Member.tsx
  nutella/src/components/MemberInput/index.tsx
  nutella/src/components/MemberInput/styles.ts
  nutella/src/components/Modals/ProejctAddModal/index.tsx
  nutella/src/components/Modals/ProejctAddModal/styles.ts
  nutella/src/components/Mypage/Contents/Project.tsx
  nutella/src/components/Mypage/Contents/styles.ts
  nutella/src/components/TagInput/index.tsx
  nutella/src/components/TagInput/styles.ts
  nutella/src/constant/UniqueId.ts
  nutella/src/constant/index.ts
  nutella/src/hooks/useTagInput.ts
Labels: new, publishing

#48 47 Realize Markdown Editor
  nutella/src/components/MarkdownEditor/Row.tsx
  nutella/src/components/MarkdownEditor/index.tsx
  nutella/src/components/MarkdownEditor/styles.ts
  nutella/src/components/MarkdownRender/styles.ts
  nutella/src/components/Providers/MarkdownProvider.tsx
  nutella/src/constant/MarkdownStyle.ts
  nutella/src/context/MarkdownCotext.ts
Labels: new

#50 49 Fix Import Error
  nutella/src/components/Providers/MarkdownProvider.tsx
  nutella/src/constant/UniqueId.ts
Labels: bug
