Repository DSM-TeaMit/Nutella, pull requests merged in 2022-02, with the labels that each got.

#56 26 Publishing Signup
  nutella/src/assets/icons/index.ts
  nutella/src/assets/icons/leftArrow.svg
  nutella/src/components/Login/Login.tsx
  nutella/src/components/Login/styles.ts
  nutella/src/components/LoginBackground/index.tsx
  nutella/src/components/LoginBackground/styles.ts
  nutella/src/components/Signup/Signup.tsx
  nutella/src/components/Signup/styles.ts
  nutella/src/container/Login/index.tsx
  nutella/src/container/Signup/index.tsx
  nutella/src/container/index.ts
  nutella/src/route/MainRouter.tsx
Labels: publishing

#59 58 Publishing Detailed Project
  nutella/src/assets/icons/index.ts
  nutella/src/assets/icons/plus.svg
  nutella/src/components/ProjectDetail/Aside/index.tsx
  nutella/src/components/ProjectDetail/Aside/styles.ts
  nutella/src/components/ProjectDetail/Comment/index.tsx
  nutella/src/components/ProjectDetail/Comment/styles.ts
  nutella/src/components/ProjectDetail/ProjectDetail.tsx
  nutella/src/components/ProjectDetail/SubmitContent/index.tsx
  nutella/src/components/ProjectDetail/SubmitContent/styles.ts
  nutella/src/components/ProjectDetail/Top/index.tsx
  nutella/src/components/ProjectDetail/Top/styles.ts
  nutella/src/components/ProjectDetail/styles.ts
  nutella/src/container/ProjectDetail/index.tsx
  nutella/src/container/index.ts
  nutella/src/route/MainRouter.tsx
Labels: publishing

#60 Publishing Project Plan UI
  nutella/src/assets/icons/check.svg
  nutella/src/assets/icons/index.ts
  nutella/src/components/CheckBox/index.tsx
  nutella/src/components/CheckBox/styles.ts
  nutella/src/components/Comment/index.tsx
  nutella/src/components/Comment/styles.ts
  nutella/src/components/CommentInput/index.tsx
  nutella/src/components/CommentInput/styles.ts
  nutella/src/components/Modals/DatePicker/DateCell.tsx
  nutella/src/components/Modals/DatePicker/index.tsx
  nutella/src/components/Modals/DatePicker/styles.ts
  nutella/src/components/Plan/Personal.tsx
  nutella/src/components/Plan/Team.tsx
  nutella/src/components/Plan/styles.ts
  nutella/src/container/Plan/index.tsx
  nutella/src/container/index.ts
  nutella/src/hooks/useThemeContext.ts
  nutella/src/interface/CommentType.ts
  nutella/src/route/MainRouter.tsx
Labels: publishing

#63 61 Fix Merge Error
  nutella/src/route/MainRouter.tsx
Labels: bug

#65 55 Fix Markdown Editor Ordered List Order Bug
  nutella/src/components/MarkdownEditor/Row.tsx
Labels: bug

#64 62 Publishing Result UI
  nutella/src/components/Result/Content/AddPage.tsx
  nutella/src/components/Result/Content/ContentExample.tsx
  nutella/src/components/Result/Content/Cover.tsx
  nutella/src/components/Result/Content/SubmitResult/FileContent.tsx
  nutella/src/components/Result/Content/SubmitResult/index.tsx
  nutella/src/components/Result/Content/SubmitResult/styles.ts
  nutella/src/components/Result/Personal.tsx
  nutella/src/components/Result/Team.tsx
  nutella/src/components/Result/styles.ts
  nutella/src/container/Result/index.tsx
  nutella/src/container/index.ts
  nutella/src/route/MainRouter.tsx
Labels: publishing

#67 27 Publishing Feed
  nutella/src/components/Feed/Feed.tsx
  nutella/src/components/Feed/FeedProject/index.tsx
  nutella/src/components/Feed/FeedProject/styles.ts
  nutella/src/components/Feed/styles.ts
  nutella/src/container/Feed/index.tsx
  nutella/src/container/index.ts
  nutella/src/interface/FeedTitle.ts
  nutella/src/route/MainRouter.tsx
Labels: publishing

#69 68 Publishing ProjectDetailModal
  nutella/src/components/Modals/ProjectDelete/index.tsx
  nutella/src/components/Modals/ProjectDelete/styles.ts
  nutella/src/components/Modals/ProjectInfoModify/index.tsx
  nutella/src/components/Modals/ProjectInfoModify/styles.ts
  nutella/src/components/Modals/ProjectMemberModify/index.tsx
  nutella/src/components/Modals/ProjectMemberModify/styles.ts
  nutella/src/components/ProjectDetail/Aside/index.tsx
  nutella/src/components/ProjectDetail/Aside/styles.ts
  nutella/src/components/ProjectDetail/Top/index.tsx
  nutella/src/components/ProjectDetail/Top/styles.ts
Labels: publishing

#73 72 React-Query Initial Setting
  nutella/src/App.tsx
Labels: style

#75 74 Add Uri
  nutella/src/class/URI.ts
  nutella/src/constant/Uri.ts
Labels: new

#78 54 Add Detail Function In Markdown Editor
  nutella/package-lock.json
  nutella/package.json
  nutella/src/assets/icons/handle.svg
  nutella/src/class/URI.ts
  nutella/src/components/Img.tsx
  nutella/src/components/MarkdownEditor/Image/index.tsx
  nutella/src/components/MarkdownEditor/Image/styles.ts
  nutella/src/components/MarkdownEditor/Popup/index.tsx
  nutella/src/components/MarkdownEditor/Popup/styles.ts
  nutella/src/components/MarkdownEditor/Row/index.tsx
  nutella/src/components/MarkdownEditor/Row/styles.ts
  nutella/src/components/MarkdownEditor/index.tsx
  nutella/src/components/MarkdownEditor/styles.ts
  nutella/src/components/Plan/Personal.tsx
  nutella/src/components/Plan/Team.tsx
  nutella/src/components/Providers/MarkdownProvider.tsx
  nutella/src/constant/BaseUrl.ts
  nutella/src/constant/Uri.ts
  nutella/src/context/MarkdownCotext.ts
  nutella/src/interface/Tag.ts
  nutella/src/utils/api/Image.ts
  nutella/src/utils/api/index.ts
  nutella/src/utils/axios/index.ts
  nutella/src/utils/axios/refresh.ts
Labels: modify

#85 81 Plan Report Api
  nutella/src/queries/Plan.ts
  nutella/src/queries/User.ts
  nutella/src/utils/api/Plan.ts
  nutella/src/utils/api/User.ts
Labels: new

#86 82 Result Report Api
  nutella/src/constant/Uri.ts
  nutella/src/queries/Result.ts
  nutella/src/utils/api/Result.ts
Labels: new

#87 84 Add Image Query
  nutella/src/components/Img.tsx
  nutella/src/components/MarkdownEditor/Image/index.tsx
  nutella/src/queries/Image.ts
  nutella/src/utils/api/Image.ts
Labels: modify

#93 92 Implement Comment Container Component
  nutella/package-lock.json
  nutella/package.json
  nutella/src/assets/icons/index.ts
  nutella/src/assets/icons/more.svg
  nutella/src/components/Comment/index.tsx
  nutella/src/components/Comment/styles.ts
  nutella/src/components/CommentContainer/index.tsx
  nutella/src/components/CommentContainer/styles.ts
  nutella/src/components/CommentInput/index.tsx
  nutella/src/components/CommentInput/styles.ts
  nutella/src/components/Plan/Personal.tsx
  nutella/src/components/Plan/Team.tsx
  nutella/src/components/Plan/styles.ts
  nutella/src/components/ProjectDetail/ProjectDetail.tsx
  nutella/src/components/Result/Personal.tsx
  nutella/src/components/Result/Team.tsx
  nutella/src/components/Result/styles.ts
  nutella/src/interface/CommentSource.ts
  nutella/src/interface/CommentStyleType.ts
  nutella/src/interface/CommentType.ts
  nutella/src/queries/Comment.ts
  nutella/src/utils/api/Comment.ts
Labels: new

#94 76 Signup API
  nutella/src/components/Login/Login.tsx
  nutella/src/components/Login/styles.ts
  nutella/src/components/Signup/Signup.tsx
  nutella/src/container/GithubLoading/index.tsx
  nutella/src/container/SignupLoading/index.tsx
  nutella/src/container/index.ts
  nutella/src/queries/Signup.ts
  nutella/src/route/MainRouter.tsx
  nutella/src/utils/api/Signup.ts
  nutella/src/utils/axios/refresh.ts
Labels: new
