Repository DSM-TeaMit/Nutella, pull requests merged in 2022-04, with the labels that each got.

#188 184 Add Row In Reports
  src/components/Cards/MainProjectCard/index.tsx
  src/components/Cards/MainProjectCard/styles.ts
  src/components/Cards/ReportCard/index.tsx
  src/components/Img.tsx
  src/components/Profile/Mypage/Contents/Project.tsx
  src/components/Profile/Mypage/Contents/Report.tsx
  src/components/Profile/Mypage/Contents/ReportAccordion/index.tsx
  src/interface/Report.ts
  src/interface/ReportPathType.ts
  src/utils/api/User.ts
Labels: modify

#192 190 Change Report With Report Status
  src/components/CheckBox/index.tsx
  src/components/Modals/AddAdminAccount/index.tsx
  src/components/PendingReport/index.tsx
  src/components/PendingReport/styles.ts
  src/components/Plan/index.tsx
  src/components/Plan/styles.ts
  src/components/Result/Content/Cover.tsx
  src/components/Result/index.tsx
  src/components/Result/styles.ts
  src/constant/ReportStatusMessage.ts
  src/interface/ReportStatus.ts
  src/queries/Admin.ts
  src/queries/Plan.ts
  src/queries/Result.ts
  src/style/globalStyle.ts
  src/utils/api/Admin.ts
  src/utils/api/Plan.ts
  src/utils/api/Result.ts
Labels: modify

#195 194 Fix Error On Delete Admin
  src/components/Img/index.tsx
  src/components/Img/styles.ts
  src/components/MarkdownEditor/Image/index.tsx
  src/components/MarkdownEditor/Popup/index.tsx
  src/components/MarkdownEditor/Row/index.tsx
  src/components/Providers/MarkdownProvider.tsx
  src/constant/Uri.ts
  src/queries/Plan.ts
  src/queries/Result.ts
  src/utils/api/Admin.ts
Labels: bug

#198 132 Implement PDF Download Function In Result And Plan
  package-lock.json
  package.json
  src/components/MarkdownEditor/Row/styles.ts
  src/components/Plan/index.tsx
  src/components/Result/index.tsx
  src/components/Result/styles.ts
  src/style/globalStyle.ts
  yarn.lock
Labels: new

#199 197 Change The Code To Import Index
  src/components/Cards/PendingReportCard/index.tsx
  src/components/Cards/ProjectCard/index.tsx
  src/components/Cards/ReportCard/index.tsx
  src/components/Comment/index.tsx
  src/components/CommentContainer/index.tsx
  src/components/CommentInput/index.tsx
  src/components/MarkdownEditor/Row/index.tsx
  src/components/Plan/index.tsx
  src/components/Plan/styles.ts
  src/components/Profile/ManagementAccount/index.tsx
  src/components/Profile/Mypage/Contents/ReportAccordion/index.tsx
  src/components/Profile/Mypage/index.tsx
  src/components/Profile/User/index.tsx
  src/components/Providers/MarkdownProvider.tsx
  src/components/Result/Content/Cover.tsx
  src/components/Result/index.tsx
  src/components/Result/styles.ts
  src/components/SideBar/Admin.tsx
  src/components/SideBar/index.tsx
  src/components/TagInput/index.tsx
  src/constant/ReportStatusMessage.ts
  src/context/MarkdownCotext.ts
  src/hooks/useInput.ts
  src/hooks/useInputs.ts
  src/hooks/useTagInput.ts
  src/interface/CommentSource.tsx
  src/interface/CommentStyleType.tsx
  src/interface/Navigation.tsx
  src/interface/Pagination.tsx
  src/interface/PlanStatus.tsx
  src/interface/ProjectTypes.tsx
  src/interface/RefreshError.tsx
  src/interface/Report.ts
  src/interface/Report.tsx
  src/interface/ReportPathType.tsx
  src/interface/ReportStatus.ts
  src/interface/ReportStatus.tsx
  src/interface/State.tsx
  src/interface/Tag.tsx
  src/interface/index.ts
  src/queries/Comment.ts
  src/queries/User.ts
  src/route/MainRouter.tsx
  src/utils/api/Comment.ts
  src/utils/api/Feed.ts
  src/utils/api/PendingReport.ts
  src/utils/api/Plan.ts
  src/utils/api/Result.ts
  src/utils/api/User.ts
  src/utils/axios/refresh.ts
Labels: modify

#202 200 Result Markdown Editor Auto Save Bug
  public/index.html
  src/components/Img/index.tsx
  src/components/Img/styles.ts
  src/components/MarkdownEditor/Image/styles.ts
  src/components/Plan/index.tsx
  src/components/Result/index.tsx
Labels: bug

#204 163 Implement Add Project Feature
  src/components/Cards/ProjectCard/index.tsx
  src/components/GithubReadme/index.tsx
  src/components/Header/index.tsx
  src/components/Img/index.tsx
  src/components/MemberInput/Member.tsx
  src/components/MemberInput/MemberWithRole.tsx
  src/components/MemberInput/index.tsx
  src/components/MemberInput/styles.ts
  src/components/Modals/ProejctAdd/index.tsx
  src/components/Modals/ProejctAdd/styles.ts
  src/components/Plan/index.tsx
  src/components/Profile/Mypage/Contents/Profile.tsx
  src/components/Profile/Mypage/Contents/Project.tsx
  src/components/Profile/Mypage/Contents/ReportAccordion/index.tsx
  src/components/Profile/User/Contents/Profile.tsx
  src/components/Profile/styles.ts
  src/components/Result/index.tsx
  src/components/SideBar/Admin.tsx
  src/components/SideBar/index.tsx
  src/components/TagInput/index.tsx
  src/constant/Uri.ts
  src/queries/Plan.ts
  src/queries/Project.ts
  src/queries/Result.ts
  src/queries/User.ts
  src/utils/api/Project.ts
  src/utils/api/User.ts
Labels: new

#208 187 Delete Unused Photos
  src/assets/icons/index.ts
  src/assets/icons/line.svg
  src/assets/icons/profile.svg
  src/assets/icons/projectPhoto.svg
Labels: modify

#207 206 Bug On The Screen Admin Login
  package-lock.json
  src/assets/icons/eye_off.svg
  src/assets/icons/eye_on.svg
  src/assets/icons/index.ts
  src/components/Modals/ProjectDelete/index.tsx
  src/components/TeacherLogin/index.tsx
  src/components/TeacherLogin/styles.ts
  src/constant/Uri.ts
  src/queries/Project.ts
  src/utils/api/Project.ts
Labels: bug

#209 🍫 (#163) - add detail
  src/components/Cards/ProjectCard/styles.ts
  src/components/Login/index.tsx
  src/components/MarkdownEditor/Image/index.tsx
  src/components/MarkdownEditor/Popup/index.tsx
  src/components/MarkdownEditor/Row/index.tsx
  src/components/MarkdownEditor/index.tsx
  src/components/Plan/index.tsx
  src/components/Providers/MarkdownProvider.tsx
  src/components/Result/index.tsx
  src/constant/BaseUrl.ts
  src/context/MarkdownContext.ts
  src/utils/api/Plan.ts
  src/utils/api/Result.ts
Labels: refactoring

#211 210 Fix Display Font Issue
  public/index.html
  src/utils/theme/theme.ts
Labels: bug

#215 214 Fix Display Modal Error
  src/components/ModalPortal/index.tsx
  src/components/Providers/ModalProvider.tsx
  src/context/ModalContext.ts
Labels: bug

#219 213 Project Detail View Bug
  src/components/Profile/Mypage/index.tsx
  src/components/ProjectDetail/Aside/styles.ts
  src/components/ProjectDetail/SubmitContent/index.tsx
  src/components/ProjectDetail/SubmitContent/styles.ts
  src/components/ProjectDetail/Top/index.tsx
  src/components/ProjectDetail/Top/styles.ts
  src/components/ProjectDetail/index.tsx
  src/components/ProjectDetail/styles.ts
  src/constant/Uri.ts
  src/queries/ProjectDetails.ts
  src/utils/api/ProjectDetails.ts
Labels: bug

#218 217 Comments Bug
  src/components/Comment/index.tsx
  src/components/Comment/styles.ts
  src/components/CommentInput/index.tsx
  src/utils/api/Comment.ts
  src/utils/api/User.ts
Labels: bug

#223 164 Implement Upload FIle On Result
  src/components/Comment/index.tsx
  src/components/CommentInput/index.tsx
  src/components/MarkdownEditor/Popup/index.tsx
  src/components/MarkdownEditor/Row/index.tsx
  src/components/Plan/index.tsx
  src/components/Result/Content/SubmitResult/FileContent.tsx
  src/components/Result/Content/SubmitResult/index.tsx
  src/components/Result/Content/SubmitResult/styles.ts
  src/components/Result/index.tsx
  src/container/Login.tsx
  src/queries/Result.ts
  src/utils/api/Result.ts
Labels: new

#224 221 Modify Project Img
  src/components/Img/index.tsx
  src/components/Modals/ProjectDelete/index.tsx
  src/components/ProjectDetail/Top/index.tsx
  src/components/ProjectDetail/Top/styles.ts
  src/components/ProjectDetail/index.tsx
  src/constant/Uri.ts
  src/queries/ProjectDetails.ts
  src/utils/api/Image.ts
  src/utils/api/ProjectDetails.ts
Labels: modify

#226 164 Implement Upload FIle On Result
  src/components/MarkdownEditor/Image/styles.ts
  src/components/Profile/Mypage/Contents/Profile.tsx
  src/components/Profile/Mypage/Contents/ReportAccordion/index.tsx
  src/components/Profile/Skeletons/ProfileSkleton/index.tsx
  src/components/Profile/Skeletons/ProfileSkleton/styles.ts
  src/components/Profile/User/Contents/Profile.tsx
  src/components/Profile/User/Contents/Project.tsx
  src/components/Result/Content/SubmitResult/index.tsx
  src/components/Result/index.tsx
  src/components/Search/Pagination/index.tsx
  src/components/Search/Pagination/styles.ts
  src/components/Search/index.tsx
  src/components/Search/styles.ts
  src/constant/QueryKeys.ts
  src/constant/Uri.ts
  src/queries/Result.ts
  src/queries/Search.ts
  src/queries/User.ts
  src/utils/api/Result.ts
  src/utils/api/Search.ts
Labels: bug, modify

#228 220 Modify Project Detail SubmitContent
  src/components/ProjectDetail/Skeleton/Aside/index.tsx
  src/components/ProjectDetail/Skeleton/Aside/styles.ts
  src/components/ProjectDetail/Skeleton/Comment/index.tsx
  src/components/ProjectDetail/Skeleton/Comment/styles.ts
  src/components/ProjectDetail/Skeleton/SubmitContent/index.tsx
  src/components/ProjectDetail/Skeleton/SubmitContent/styles.ts
  src/components/ProjectDetail/Skeleton/Top/index.tsx
  src/components/ProjectDetail/Skeleton/Top/styles.ts
  src/components/ProjectDetail/Skeleton/index.tsx
  src/components/ProjectDetail/Skeleton/styles.ts
  src/components/ProjectDetail/SubmitContent/index.tsx
  src/components/ProjectDetail/SubmitContent/styles.ts
  src/components/ProjectDetail/Top/styles.ts
  src/components/ProjectDetail/index.tsx
  src/utils/api/ProjectDetails.ts
Labels: modify

#229 227 Refactoring Pagination
  src/components/Cards/ReportSkeleton/index.tsx
  src/components/Cards/ReportSkeleton/styles.ts
  src/components/Feed/index.tsx
  src/components/PendingReport/index.tsx
  src/components/Profile/Mypage/Contents/Project.tsx
  src/components/Profile/Mypage/Contents/ReportAccordion/index.tsx
  src/components/Profile/User/Contents/Project.tsx
  src/components/Search/index.tsx
  src/constant/Limit.ts
  src/hooks/usePagination.ts
  src/queries/Feed.ts
  src/queries/PendingReport.ts
  src/queries/Search.ts
  src/queries/User.ts
Labels: refactoring

#230 201 Implement Project Details Modal
  src/components/Img/index.tsx
  src/components/Modals/ProjectDelete/index.tsx
  src/components/Modals/ProjectInfoModify/index.tsx
  src/components/Modals/ProjectInfoModify/styles.ts
  src/components/Modals/ProjectMemberModify/index.tsx
  src/components/Modals/ProjectMemberModify/styles.ts
  src/components/ProjectDetail/Top/index.tsx
  src/queries/Project.ts
Labels: new

#234 233 Implement Upload Student Excel File
  src/components/Profile/ManagementAccount/index.tsx
  src/components/Profile/ManagementAccount/styles.ts
  src/constant/Uri.ts
  src/queries/Admin.ts
  src/utils/api/Admin.ts
Labels: bug

#236 235 Fix Bug
  src/components/CommentInput/index.tsx
  src/components/Feed/index.tsx
  src/components/FeedList/index.tsx
  src/components/FeedList/styles.ts
  src/components/Img/index.tsx
  src/components/MarkdownEditor/Row/styles.ts
  src/components/MarkdownEditor/styles.ts
  src/components/Modals/ProjectDelete/index.tsx
  src/components/PendingReport/index.tsx
  src/components/Plan/index.tsx
  src/components/Profile/ManagementAccount/index.tsx
  src/components/Profile/Mypage/Contents/Report.tsx
  src/components/Profile/Mypage/Contents/ReportAccordion/index.tsx
  src/components/Profile/Skeletons/ReportSkeleton/index.tsx
  src/components/Profile/Skeletons/ReportSkeleton/styles.ts
  src/components/ProjectDetail/Skeleton/styles.ts
  src/components/ProjectDetail/Top/index.tsx
  src/components/ProjectDetail/Top/styles.ts
  src/components/ProjectDetail/index.tsx
  src/components/Providers/ModalProvider.tsx
  src/components/Result/Content/SubmitResult/index.tsx
  src/components/Result/Content/SubmitResult/styles.ts
  src/components/Result/index.tsx
  src/constant/QueryKeys.ts
  src/context/ModalContext.ts
  src/queries/Comment.ts
  src/queries/Feed.ts
  src/queries/Project.ts
  src/queries/Result.ts
  src/utils/api/Feed.ts
  src/utils/api/Image.ts
  src/utils/api/ProjectDetails.ts
Labels: bug

#237 201 Implement Project Details Modal
  src/components/CommentInput/index.tsx
  src/components/MemberInput/ChangeMemberRole.tsx
  src/components/MemberInput/styles.ts
  src/components/Modals/ProjectInfoModify/index.tsx
  src/components/Modals/ProjectInfoModify/styles.ts
  src/components/Modals/ProjectMemberModify/Member.tsx
  src/components/Modals/ProjectMemberModify/index.tsx
  src/components/Modals/ProjectMemberModify/styles.ts
  src/components/Profile/Mypage/Contents/Setting.tsx
  src/components/ProjectDetail/SubmitContent/index.tsx
  src/components/ProjectDetail/SubmitContent/styles.ts
  src/components/SideBar/Admin.tsx
  src/utils/api/Project.ts
Labels: bug, new
