Repository DSM-TeaMit/Nutella, pull requests merged in 2022-03, with the labels that each got.

#99 98 Pending Report UI
  nutella/src/components/PendingReport/index.tsx
  nutella/src/components/PendingReport/styles.ts
  nutella/src/components/PendingReportCard/index.tsx
  nutella/src/components/PendingReportCard/styles.ts
  nutella/src/container/PendingReport/index.tsx
  nutella/src/container/index.ts
  nutella/src/route/MainRouter.tsx
Labels: new

#102 95 Signup Code Fix
  nutella/src/components/Modals/ProjectDelete/index.tsx
  nutella/src/components/Modals/ProjectDelete/styles.ts
  nutella/src/components/Modals/ProjectInfoModify/index.tsx
  nutella/src/components/Modals/ProjectInfoModify/styles.ts
  nutella/src/components/ProjectDetail/Comment/index.tsx
  nutella/src/components/ProjectDetail/Comment/styles.ts
  nutella/src/components/Signup/Signup.tsx
  nutella/src/components/Signup/styles.ts
  nutella/src/components/TeacherLogin/TeacherLogin.tsx
  nutella/src/components/TeacherLogin/styles.ts
  nutella/src/container/GithubLoading/index.tsx
  nutella/src/container/SignLoading/index.tsx
  nutella/src/container/SignupLoading/index.tsx
  nutella/src/container/index.ts
  nutella/src/queries/Signup.ts
  nutella/src/route/MainRouter.tsx
  nutella/src/utils/api/Signup.ts
  nutella/src/utils/axios/refresh.ts
Labels: modify

#104 100 Copy Paste Bug In Markdown Editor
  nutella/src/components/MarkdownEditor/Row/index.tsx
  nutella/src/route/MainRouter.tsx
Labels: bug

#110 109 ReImplement Login Logic And Create User Context
  nutella/src/App.tsx
  nutella/src/components/Message/PositiveMessage.tsx
  nutella/src/components/Providers/UserProvider.tsx
  nutella/src/constant/Uri.ts
  nutella/src/container/SignLoading/index.tsx
  nutella/src/container/SignLoading/styles.ts
  nutella/src/context/UserContext.ts
  nutella/src/hooks/useUserContext.ts
  nutella/src/queries/Signup.ts
  nutella/src/utils/api/Signup.ts
  nutella/src/utils/axios/index.ts
Labels: modify

#114 112 Implement Refresh Token
  nutella/package.json
  nutella/src/App.tsx
  nutella/src/constant/StorageKeys.ts
  nutella/src/constant/Uri.ts
  nutella/src/interface/RefreshError.ts
  nutella/src/queries/Signup.ts
  nutella/src/route/MainRouter.tsx
  nutella/src/utils/axios/index.ts
  nutella/src/utils/axios/refresh.ts
  nutella/yarn.lock
Labels: modify

#116 106 Merge Google Button On Login
  nutella/src/components/Login/Login.tsx
  nutella/src/components/Login/styles.ts
  nutella/src/container/Login/index.tsx
Labels: modify

#118 117 TeacherLogin Btn Modify
  nutella/src/components/TeacherLogin/styles.ts
Labels: modify

#120 88 Use Api On My Page
  nutella/src/App.tsx
  nutella/src/components/CommentInput/index.tsx
  nutella/src/components/CommentInput/styles.ts
  nutella/src/components/GithubReadme/index.tsx
  nutella/src/components/GithubReadme/styles.ts
  nutella/src/components/Modals/AccountDeleteModal/index.tsx
  nutella/src/components/Modals/AccountDeleteModal/styles.ts
  nutella/src/components/Modals/GithubIdModal/index.tsx
  nutella/src/components/Modals/GithubIdModal/styles.ts
  nutella/src/components/Modals/ProejctAddModal/index.tsx
  nutella/src/components/Profile/Error.tsx
  nutella/src/components/Profile/Loading.tsx
  nutella/src/components/Profile/Mypage/Contents/Profile.tsx
  nutella/src/components/Profile/Mypage/Contents/Project.tsx
  nutella/src/components/Profile/Mypage/Contents/Report.tsx
  nutella/src/components/Profile/Mypage/Contents/ReportAccordion/index.tsx
  nutella/src/components/Profile/Mypage/Contents/ReportAccordion/styles.ts
  nutella/src/components/Profile/Mypage/Contents/Setting.tsx
  nutella/src/components/Profile/Mypage/Contents/styles.ts
  nutella/src/components/Profile/Mypage/index.tsx
  nutella/src/components/Profile/User/Contents/Profile.tsx
  nutella/src/components/Profile/User/Contents/Project.tsx
  nutella/src/components/Profile/User/index.tsx
  nutella/src/components/Profile/styles.ts
  nutella/src/components/ProjectCard/index.tsx
  nutella/src/components/ProjectCard/styles.ts
  nutella/src/components/Providers/UserProvider.tsx
  nutella/src/components/ReportCard/index.tsx
  nutella/src/components/ReportCard/styles.ts
  nutella/src/components/SideBar/Navigation/index.tsx
  nutella/src/components/SideBar/index.tsx
  nutella/src/components/SideBar/styles.ts
  nutella/src/constant/IsMore.ts
  nutella/src/constant/Uri.ts
  nutella/src/context/UserContext.ts
  nutella/src/hooks/useUserContext.ts
  nutella/src/interface/Report.ts
  nutella/src/interface/ReportPathType.ts
  nutella/src/queries/Signup.ts
  nutella/src/queries/User.ts
  nutella/src/route/RouterWithDefaultComponent.tsx
  nutella/src/utils/api/User.ts
Labels: modify

#122 113 Management Query Key By Constant
  nutella/src/constant/QueryKeys.ts
  nutella/src/queries/Comment.ts
  nutella/src/queries/Image.ts
  nutella/src/queries/Plan.ts
  nutella/src/queries/Result.ts
  nutella/src/queries/Signup.ts
  nutella/src/queries/User.ts
Labels: new

#123 115 Remove Message Context
  nutella/src/App.tsx
  nutella/src/components/Comment/index.tsx
  nutella/src/components/CommentInput/index.tsx
  nutella/src/components/Message/DenialMessage.tsx
  nutella/src/components/Message/PositiveMessage.tsx
  nutella/src/components/Message/styles.ts
  nutella/src/components/MessageController/index.tsx
  nutella/src/components/MessageController/styles.ts
  nutella/src/components/Modals/AccountDeleteModal/index.tsx
  nutella/src/components/Providers/MarkdownProvider.tsx
  nutella/src/components/Providers/MessageProvider.tsx
  nutella/src/container/GithubLoading/index.tsx
  nutella/src/container/SignLoading/index.tsx
  nutella/src/context/MessageContext.ts
  nutella/src/hooks/useMessageContext.ts
  nutella/src/queries/Signup.ts
Labels: modify

#124 119 Remove Refetch On Image
  nutella/package.json
  nutella/src/components/Img.tsx
  nutella/src/queries/Image.ts
  nutella/yarn.lock
Labels: modify

#130 125 Management Account UI
  nutella/src/components/Modals/AddAdminAccount/index.tsx
  nutella/src/components/Modals/AddAdminAccount/styles.ts
  nutella/src/components/Profile/ManagementAccount/Account/index.tsx
  nutella/src/components/Profile/ManagementAccount/Account/styles.ts
  nutella/src/components/Profile/ManagementAccount/index.tsx
  nutella/src/components/Profile/ManagementAccount/styles.ts
  nutella/src/components/SideBar/Admin.tsx
  nutella/src/container/ManagementAccount.tsx
  nutella/src/container/index.ts
  nutella/src/route/RouterWithDefaultComponent.tsx
Labels: publishing

#140 128 Change File Name And Folder Structure
  nutella/src/components/Feed/index.tsx
  nutella/src/components/Login/index.tsx
  nutella/src/components/Modals/AccountDelete/index.tsx
  nutella/src/components/Modals/AccountDelete/styles.ts
  nutella/src/components/Modals/GithubId/index.tsx
  nutella/src/components/Modals/GithubId/styles.ts
  nutella/src/components/Modals/ProejctAdd/index.tsx
  nutella/src/components/Modals/ProejctAdd/styles.ts
  nutella/src/components/Profile/Mypage/Contents/Project.tsx
  nutella/src/components/Profile/Mypage/Contents/Setting.tsx
  nutella/src/components/ProjectDetail/index.tsx
  nutella/src/components/Search/index.tsx
  nutella/src/components/Signup/index.tsx
  nutella/src/components/TeacherLogin/index.tsx
  nutella/src/container/Feed.tsx
  nutella/src/container/GithubLoading.tsx
  nutella/src/container/Login.tsx
  nutella/src/container/Mypage.tsx
  nutella/src/container/PendingReport.tsx
  nutella/src/container/Plan.tsx
  nutella/src/container/ProjectDetail.tsx
  nutella/src/container/Result.tsx
  nutella/src/container/Search.tsx
  nutella/src/container/Signup.tsx
  nutella/src/container/TeacherLogin.tsx
  nutella/src/container/User.tsx
Labels: modify

#143 135 Change Login Style
  nutella/src/components/Login/index.tsx
  nutella/src/components/Login/styles.ts
  nutella/src/components/Signup/index.tsx
  nutella/src/components/Signup/styles.ts
  nutella/src/components/TeacherLogin/index.tsx
  nutella/src/components/TeacherLogin/styles.ts
Labels: modify

#144 134 Use Api On Pending Report
  nutella/.eslintrc.js
  nutella/package-lock.json
  nutella/package.json
  nutella/src/components/PendingReport/index.tsx
  nutella/src/components/PendingReport/styles.ts
  nutella/src/components/PendingReportCard/index.tsx
  nutella/src/components/Profile/Mypage/Contents/Project.tsx
  nutella/src/components/Profile/Mypage/Contents/ReportAccordion/index.tsx
  nutella/src/constant/Limit.ts
  nutella/src/constant/QueryKeys.ts
  nutella/src/constant/Uri.ts
  nutella/src/hooks/useInfiniteScroll.ts
  nutella/src/interface/Pagination.ts
  nutella/src/queries/PendingReport.ts
  nutella/src/queries/Signup.ts
  nutella/src/utils/api/PendingReport.ts
  nutella/src/utils/api/User.ts
  nutella/yarn.lock
Labels: new

#147 142 Refactoring Code By Eslint
  nutella/.eslintrc.js
  nutella/src/components/Feed/FeedProject/index.tsx
  nutella/src/components/GithubReadme/index.tsx
  nutella/src/components/MarkdownEditor/Popup/index.tsx
  nutella/src/components/MarkdownEditor/Row/index.tsx
  nutella/src/components/MarkdownEditor/Row/styles.ts
  nutella/src/components/MarkdownEditor/index.tsx
  nutella/src/components/ModalPortal/index.tsx
  nutella/src/components/Modals/AccountDelete/index.tsx
  nutella/src/components/Modals/DatePicker/DateCell.tsx
  nutella/src/components/Modals/ProjectInfoModify/index.tsx
  nutella/src/components/PendingReport/index.tsx
  nutella/src/components/PendingReportCard/index.tsx
  nutella/src/components/Profile/ManagementAccount/index.tsx
  nutella/src/components/Profile/Mypage/Contents/Profile.tsx
  nutella/src/components/Profile/Mypage/Contents/Project.tsx
  nutella/src/components/Profile/Mypage/Contents/ReportAccordion/index.tsx
  nutella/src/components/Profile/Mypage/Contents/ReportAccordion/styles.ts
  nutella/src/components/Profile/User/Contents/Profile.tsx
  nutella/src/components/Profile/User/Contents/Project.tsx
  nutella/src/components/Profile/User/index.tsx
  nutella/src/components/ProjectCard/index.tsx
  nutella/src/components/ProjectDetail/Top/index.tsx
  nutella/src/components/Providers/MarkdownProvider.tsx
  nutella/src/components/Providers/ModalProvider.tsx
  nutella/src/components/ReportCard/styles.ts
  nutella/src/components/Result/Personal.tsx
  nutella/src/components/Search/index.tsx
  nutella/src/components/SideBar/index.tsx
  nutella/src/components/TagInput/index.tsx
  nutella/src/constant/UniqueId.ts
  nutella/src/queries/Signup.ts
  nutella/src/queries/User.ts
  nutella/src/utils/api/Signup.ts
  nutella/src/utils/api/User.ts
  nutella/src/utils/axios/refresh.ts
Labels: refactoring

#150 149 404 Page UI
  nutella/src/container/Page404/index.tsx
  nutella/src/container/Page404/styles.ts
  nutella/src/route/RouterWithDefaultComponent.tsx
Labels: new

#148 146 Change Projects Folder Structure
  nutella/src/components/Cards/MainProjectCard/index.tsx
  nutella/src/components/Cards/MainProjectCard/styles.ts
  nutella/src/components/Cards/PendingReportCard/index.tsx
  nutella/src/components/Cards/PendingReportCard/styles.ts
  nutella/src/components/Cards/ProjectCard/index.tsx
  nutella/src/components/Cards/ProjectCard/styles.ts
  nutella/src/components/Cards/ReportCard/index.tsx
  nutella/src/components/Cards/ReportCard/styles.ts
  nutella/src/components/Feed/FeedProject/index.tsx
  nutella/src/components/PendingReport/index.tsx
  nutella/src/components/Profile/Mypage/Contents/Profile.tsx
  nutella/src/components/Profile/Mypage/Contents/Project.tsx
  nutella/src/components/Profile/Mypage/Contents/ReportAccordion/index.tsx
  nutella/src/components/Profile/User/Contents/Profile.tsx
  nutella/src/components/Profile/User/Contents/Project.tsx
  nutella/src/components/Search/index.tsx
Labels: modify

#154 153 Fix Bug On Markdown Editor
  nutella/src/components/MarkdownEditor/Row/index.tsx
Labels: bug

#155 137 Implement Github OAuth
  nutella/src/components/Signup/index.tsx
  nutella/src/container/GithubLoading.tsx
  nutella/src/container/GithubLoading/index.tsx
  nutella/src/container/GithubLoading/styles.ts
  nutella/src/queries/Signup.ts
  nutella/src/route/MainRouter.tsx
  nutella/src/utils/api/Signup.ts
Labels: modify

#157 145 Add Thumbnail
  nutella/src/App.tsx
  nutella/src/components/Cards/ProjectCard/index.tsx
  nutella/src/components/Cards/ReportCard/index.tsx
  nutella/src/utils/api/User.ts
Labels: modify

#160 136 Change Feed Style
  nutella/src/components/Cards/MainProjectCard/index.tsx
  nutella/src/components/Cards/MainProjectCard/styles.ts
  nutella/src/components/Feed/FeedProject/styles.ts
  nutella/src/components/Feed/styles.ts
Labels: modify

#161 139 Change Project Style
  nutella/package-lock.json
  nutella/package.json
  nutella/src/components/Modals/ProjectInfoModify/index.tsx
  nutella/src/components/Modals/ProjectInfoModify/styles.ts
  nutella/src/components/Modals/ProjectMemberModify/index.tsx
  nutella/src/components/Modals/ProjectMemberModify/styles.ts
  nutella/src/components/ProjectDetail/Comment/index.tsx
  nutella/src/components/ProjectDetail/Comment/styles.ts
  nutella/src/components/ProjectDetail/index.tsx
  nutella/src/components/ProjectDetail/styles.ts
Labels: modify

#166 97 Implement Header Function
  nutella/src/components/Header/SearchInput/index.tsx
  nutella/src/components/Header/SearchInput/styles.ts
  nutella/src/components/Header/index.tsx
  nutella/src/components/Header/styles.ts
  nutella/src/components/Profile/Mypage/Contents/styles.ts
  nutella/src/constant/QueryKeys.ts
  nutella/src/constant/Uri.ts
  nutella/src/queries/Plan.ts
  nutella/src/queries/User.ts
  nutella/src/utils/api/User.ts
Labels: new

#167 162 Add 404 Page On Mypage, User And Project
  nutella/src/components/Profile/Mypage/index.tsx
  nutella/src/components/Profile/NotFound.tsx
  nutella/src/components/Profile/User/index.tsx
  nutella/src/components/Profile/styles.ts
  nutella/src/route/RouterWithDefaultComponent.tsx
Labels: new

#170 168 Implement Management Account Feature
  nutella/src/components/Modals/AddAdminAccount/index.tsx
  nutella/src/components/Modals/AddAdminAccount/styles.ts
  nutella/src/components/Profile/ManagementAccount/Account/index.tsx
  nutella/src/components/Profile/ManagementAccount/index.tsx
  nutella/src/components/Profile/styles.ts
  nutella/src/constant/QueryKeys.ts
  nutella/src/constant/Uri.ts
  nutella/src/queries/Admin.ts
  nutella/src/utils/api/Admin.ts
Labels: new

#171 127 Exception Handling Of Access Rights On My Page
  nutella/src/components/Profile/Mypage/index.tsx
Labels: new

#174 172 Add Favicon And Change Title By Page
  nutella/public/android-icon-144x144.png
  nutella/public/android-icon-192x192.png
  nutella/public/android-icon-36x36.png
  nutella/public/android-icon-48x48.png
  nutella/public/android-icon-72x72.png
  nutella/public/android-icon-96x96.png
  nutella/public/apple-icon-114x114.png
  nutella/public/apple-icon-120x120.png
  nutella/public/apple-icon-144x144.png
  nutella/public/apple-icon-152x152.png
  nutella/public/apple-icon-180x180.png
  nutella/public/apple-icon-57x57.png
  nutella/public/apple-icon-60x60.png
  nutella/public/apple-icon-72x72.png
  nutella/public/apple-icon-76x76.png
  nutella/public/apple-icon-precomposed.png
  nutella/public/apple-icon.png
  nutella/public/browserconfig.xml
  nutella/public/favicon-16x16.png
  nutella/public/favicon-32x32.png
  nutella/public/favicon-96x96.png
  nutella/public/favicon.ico
  nutella/public/index.html
  nutella/public/logo192.png
  nutella/public/logo512.png
  nutella/public/manifest.json
  nutella/public/ms-icon-144x144.png
  nutella/public/ms-icon-150x150.png
  nutella/public/ms-icon-310x310.png
  nutella/public/ms-icon-70x70.png
  nutella/src/components/Header/index.tsx
  nutella/src/components/Header/styles.ts
  nutella/src/components/Plan/index.tsx
  nutella/src/components/Profile/User/index.tsx
  nutella/src/components/Profile/styles.ts
  nutella/src/components/ProjectDetail/index.tsx
  nutella/src/components/Result/index.tsx
  nutella/src/components/Search/index.tsx
  nutella/src/components/Signup/index.tsx
  nutella/src/components/TeacherLogin/index.tsx
  nutella/src/container/Feed.tsx
  nutella/src/container/Login.tsx
  nutella/src/container/ManagementAccount.tsx
  nutella/src/container/Mypage.tsx
  nutella/src/container/Page404/index.tsx
  nutella/src/container/PendingReport.tsx
  nutella/src/hooks/useTitle.ts
  nutella/src/utils/api/Result.ts
Labels: new

#175 141 Implement Teacher Login Function
  nutella/src/components/Signup/index.tsx
  nutella/src/components/TeacherLogin/index.tsx
  nutella/src/queries/Login.ts
  nutella/src/utils/api/Login.ts
Labels: new

#177 173 Modal Won't Close When Clicked Backdrop
  nutella/src/components/ModalPortal/index.tsx
Labels: bug

#179 178 Changing The AdminLogin Code File
  nutella/src/components/TeacherLogin/index.tsx
  nutella/src/queries/Admin.ts
  nutella/src/queries/Login.ts
  nutella/src/utils/api/Admin.ts
  nutella/src/utils/api/Login.ts
Labels: modify

#180 138 Implement Change Github Id Function
  nutella/src/components/Cards/PendingReportCard/styles.ts
  nutella/src/components/Cards/ProjectCard/index.tsx
  nutella/src/components/Cards/ProjectCard/styles.ts
  nutella/src/components/Cards/ReportCard/styles.ts
  nutella/src/components/Header/styles.ts
  nutella/src/components/Loading/index.tsx
  nutella/src/components/Loading/styles.ts
  nutella/src/components/Modals/GithubId/index.tsx
  nutella/src/components/Modals/GithubId/styles.ts
  nutella/src/components/PendingReport/index.tsx
  nutella/src/components/Profile/Mypage/Contents/Profile.tsx
  nutella/src/components/Profile/Mypage/Contents/Setting.tsx
  nutella/src/components/Profile/Mypage/Contents/styles.ts
  nutella/src/components/Profile/User/Contents/Profile.tsx
  nutella/src/components/Profile/styles.ts
  nutella/src/components/Search/index.tsx
  nutella/src/components/SideBar/Navigation/styles.ts
  nutella/src/components/Signup/index.tsx
  nutella/src/constant/GithubOAuth.ts
  nutella/src/constant/Uri.ts
  nutella/src/container/ChangeGithubIdLoading.tsx
  nutella/src/container/GithubLoading.tsx
  nutella/src/container/SignLoading.tsx
  nutella/src/container/SignLoading/styles.ts
  nutella/src/container/index.ts
  nutella/src/hooks/useTitle.ts
  nutella/src/queries/Signup.ts
  nutella/src/queries/User.ts
  nutella/src/route/MainRouter.tsx
  nutella/src/utils/api/Signup.ts
  nutella/src/utils/api/User.ts
Labels: new
